service: big-mouth

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  stage: dev
  region: ca-central-1

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - httpApi:
          path: /
          method: get

  get-restaurants:
    handler: functions/getRestaurants.handler
    events:
      - httpApi:
          path: /restaurants
          method: get
    environment:
      restaurants_table: restaurants
